/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
// TODO: remove this when the generator supports discriminators
export const a = 1;
// workaround until we upgrade the generator
export const b = 2;
